import csv
import random
import math

class Node:
    def __init__(self, value=None, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def is_terminal(self):
        return self.left is None and self.right is None

    def evaluate(self, x):
        if self.value == "x":
            return x
        
        if self.is_terminal():
            return float(self.value)
        
        left_value = self.left.evaluate(x)
        right_value = self.right.evaluate(x)

        if self.value == "+":
            return left_value + right_value
        elif self.value == "-":
            return left_value - right_value
        elif self.value == "*":
            return left_value * right_value
        elif self.value == "/":
            #incase of zero
            if abs(right_value) < 1e-10:
                return left_value
            else:
                return left_value / right_value
        else:
            raise ValueError(f"Unknown operator: {self.value}")

#find depth
    def depth(self):
      if self.is_terminal():
        return 1
      return 1 + max(self.left.depth(), self.right.depth())

#size
    def size(self):
      if self.is_terminal():
        return 1
      return 1 + self.left.size() + self.right.size()
 

  #copy of tree
    def copy(self):
      if self.is_terminal():
        return Node(self.value)
      return Node (self.value,
                   self.left.copy(),
                   self.right.copy())

# print tree (generated by Claude)
    def __str__(self):
        return "\n".join(line.rstrip() for line in self._render()[0])

    def _render(self):
        """Return (lines, width, center) where center is the column of this node's label."""
        label = str(self.value)
        if self.is_terminal():
            return [label], len(label), (len(label) - 1) // 2

        l_lines, l_w, l_c = self.left._render()
        r_lines, r_w, r_c = self.right._render()

        # Space between the two subtrees; widen by one if needed so the
        # parent can sit exactly halfway between its children.
        gap = 3
        if (l_w + gap + r_c - l_c) % 2:
            gap += 1
        r_c += l_w + gap                  # right child's column in the combined block
        mid = (l_c + r_c) // 2            # parent's column
        k = (mid - l_c + 1) // 2          # how far the / and \ sit from the parent

        height = max(len(l_lines), len(r_lines))
        l_lines = l_lines + [" " * l_w] * (height - len(l_lines))
        r_lines = r_lines + [" " * r_w] * (height - len(r_lines))
        body = [a + " " * gap + b for a, b in zip(l_lines, r_lines)]
        width = l_w + gap + r_w

        # Centre the label on `mid`, growing the block if the label overhangs.
        start = mid - (len(label) - 1) // 2
        pad_l = max(0, -start)
        pad_r = max(0, start + len(label) - width)
        start, mid, width = start + pad_l, mid + pad_l, width + pad_l + pad_r
        body = [" " * pad_l + line + " " * pad_r for line in body]

        top = (" " * start + label).ljust(width)
        branches = (" " * (mid - k) + "/" + " " * (2 * k - 1) + "\\").ljust(width)
        return [top, branches] + body, width, mid

# print individual
    def to_infix(self):
        if self.is_terminal():
            return str(self.value)
        return f"({self.left.to_infix()} {self.value} {self.right.to_infix()})"


def generate_random_tree(operators, depth=5, p_terminal=0.2, p_x=0.5):
    if depth <= 1 or random.random() < p_terminal:
        if random.random() < p_x:
            return Node("x")
        return Node(str(round(random.uniform(-10, 10), 2)))
    return Node(random.choice(operators),
                generate_random_tree(operators, depth - 1, p_terminal, p_x),
                generate_random_tree(operators, depth - 1, p_terminal, p_x))

def mutate(node, operators, p_x=0.5):
    # choose a random node to mutate
    nodes = get_all_nodes(node, [])
    mutate_node = random.choice(nodes)
    print(f"Mutating node with value: {mutate_node.value}")
    if mutate_node.is_terminal():
        # change the terminal value
        if random.random() < p_x:
            mutate_node.value = "x"
        else:
            mutate_node.value = str(round(random.uniform(-10, 10), 2)) 
    else:
        # change the operator
        mutate_node.value = random.choice(operators)
    print(f"Mutated node value: {mutate_node.value}")
    return node
        
def get_all_nodes(node, nodes):
    nodes.append(node)
    if not node.is_terminal():
        get_all_nodes(node.left, nodes)
        get_all_nodes(node.right, nodes)
    return nodes

def get_all_inner_nodes(node, nodes):
    if node.is_terminal():
        return nodes
    else:
        nodes.append(node)
        get_all_inner_nodes(node.left, nodes)
        get_all_inner_nodes(node.right, nodes)
    return nodes

def crossover(parent1, parent2, max_depth=8):
    # choose a random nodes to cross over
    nodes_1 = get_all_inner_nodes(parent1, [])
    nodes_2 = get_all_inner_nodes(parent2, []) 

    if (nodes_1 == []):
        return parent2
    elif (nodes_2 == []):
        return parent1
    else:
        swap_parent_1 = random.choice(nodes_1)
        swap_parent_2 = random.choice(nodes_2)
        if (swap_parent_2.left == None):
            subtree = swap_parent_2.right
        elif (swap_parent_2.right == None): 
            subtree = swap_parent_2.left
        else:
            subtree = random.choice([swap_parent_2.left, swap_parent_2.right])
        
        if (swap_parent_1.left == None): 
            swap_parent_1.right = subtree
        elif (swap_parent_1.right == None):
            swap_parent_1.left = subtree
        else:
            if random.random() < 0.5:
                swap_parent_1.left = subtree
            else:
                swap_parent_1.right = subtree

        if parent1.depth() > max_depth:
            return parent2
        return parent1
